branches:
  only:
  - master
python:
- 3.4
install:
- pip install -r requirements.txt --user
script:
- pelican content -s publishconf.py
- bash deploy.sh
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
  - git submodule update --init --recursive
